"""Initial schema

Revision ID: 29533358ef5c
Revises: 
Create Date: 2025-12-02 22:19:17.113890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29533358ef5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emotional_states',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('primary_emotion', sa.String(), nullable=False),
    sa.Column('energy_level', sa.Float(), nullable=False),
    sa.Column('stress_level', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('transcript_text', sa.String(), nullable=True),
    sa.Column('task_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emotional_states_id'), 'emotional_states', ['id'], unique=False)
    op.create_index(op.f('ix_emotional_states_recorded_at'), 'emotional_states', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_emotional_states_user_id'), 'emotional_states', ['user_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('original_text', sa.String(), nullable=True),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='taskpriority'), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=True),
    sa.Column('estimated_energy_cost', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='energycost'), nullable=True),
    sa.Column('emotional_context', sa.String(), nullable=True),
    sa.Column('category_type', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('location_coordinates', sa.JSON(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('suggested_time', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_category_type'), 'tasks', ['category_type'], unique=False)
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_category_type'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_emotional_states_user_id'), table_name='emotional_states')
    op.drop_index(op.f('ix_emotional_states_recorded_at'), table_name='emotional_states')
    op.drop_index(op.f('ix_emotional_states_id'), table_name='emotional_states')
    op.drop_table('emotional_states')
    # ### end Alembic commands ###

